version: '3.8'
services:
  app:
    build:
      context: . # project root
      dockerfile: ./Dockerfile
    ports:
      - "5173:5173" # map the frontend port
      - "3000:3000" # map the backend port
    volumes:
      - .:/app # mounts project files for live changes without needing to rebuild container
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/palette-db
      - NODE_ENV=development
    command: sh -c "npm run dev"